worker_processes 1;
events { worker_connections 1024; }

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  upstream web_upstream { server web:5173; }
  upstream api_upstream { server api:3000; }

  # Proper upgrade handling (HTTP vs WebSocket)
  map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
  }


  server {
    listen 80;
    server_name localhost;

    return 301 https://$host:8443$request_uri;
  }


  server {
    listen 443 ssl;
    
    server_name localhost;
    # JESS: Use this to run on mobile (wth it Nginx responds to any IP or domain name)
    # server_name localhost _ ;

    ssl_certificate     /etc/nginx/certs/dev.crt;
    ssl_certificate_key /etc/nginx/certs/dev.key;

    # ---- Static files (served directly, avoids Vite redirect quirks) ----
    location /socket-test.html {
      root /usr/share/nginx/html;
      try_files $uri =404;
    }

    # ---- Avatars ----
    location /avatars/ {
    proxy_pass http://api_upstream;
    }
    
    #location /avatars/ {
    #  root /usr/share/nginx;
    #  try_files $uri =404;
    #}

    # ---- Socket.IO (must be before /) ----
    location /socket.io/ {
      proxy_pass http://api_upstream;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;

      proxy_buffering off;
      proxy_read_timeout 60s;
      proxy_send_timeout 60s;
    }
    
    # ---- API ----
    location /api/ {
      client_max_body_size 5m;   # Added 5mb as a global limit for all API endpoints, base is 1mb which is too small for avatar uploads (added limit of 2mb for avatars in the API route itself)
      proxy_pass http://api_upstream;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }

    # ---- Web (Vite dev server) ----
    location / {
      proxy_pass http://web_upstream;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }
  }
}